services:
  trade-manager:
    build: .
    ports:
      - "${API_PORT}:${API_PORT}"  # Main API port
      - "${METRICS_PORT}:${METRICS_PORT}"  # Metrics port
    environment:
      - API_PORT=${API_PORT}
      - API_HOST=${API_HOST}
      - METRICS_PORT=${METRICS_PORT}
      - PYTHONPATH=/app
      - MARKET_ANALYSIS_HOST=${MARKET_ANALYSIS_HOST}
      - MARKET_ANALYSIS_PORT=${MARKET_ANALYSIS_PORT}
      - TRADE_DISCOVERY_HOST=${TRADE_DISCOVERY_HOST}
      - TRADE_DISCOVERY_PORT=${TRADE_DISCOVERY_PORT}
      - ENABLE_METRICS=${ENABLE_METRICS}
      - LOG_LEVEL=${LOG_LEVEL}
      - MAX_POSITION_SIZE=${MAX_POSITION_SIZE}
      - RISK_PERCENTAGE=${RISK_PERCENTAGE}
      - MAX_DRAWDOWN=${MAX_DRAWDOWN}
      - STOP_LOSS_PERCENTAGE=${STOP_LOSS_PERCENTAGE}
      - TAKE_PROFIT_PERCENTAGE=${TAKE_PROFIT_PERCENTAGE}
      - DATABASE_URL=${DATABASE_URL}
      - API_KEY=${API_KEY}
      - API_KEY_HEADER=${API_KEY_HEADER}
      - DEBUG=${DEBUG}
      - ENVIRONMENT=${ENVIRONMENT}
    volumes:
      - .:/app
    command: uvicorn src.api.main:app --host ${API_HOST} --port ${API_PORT} --reload
    networks:
      - trade_manager_net

networks:
  trade_manager_net:
    driver: bridge
